### PR TITLE
Patching lhapdf5 to avoid format security compilation error.

### PR DESCRIPTION
**Pull request by mpuccio**
I am trying to compile on Fedora 22 and on Mint 17.1 the O2 software using alibuild. 
On both the systems I got stuck due to a format security error in the compilation of lhapdf5.
This small patch solves this issue for me, but maybe you have cleaner solution.

### CODE REVIEW

**Comment by ktf** [comment]
Thank you for your fix.

IMHO what we should do, though, is to create an `alisw/lhapdf5` repository and patch it there directly, so that people can se the actual code being built. Unless you need this immediately, I'm going to do it tomorrow and integrate your patch there.

@dberzano

**Comment by dberzano** [comment]
Yes @ktf I second that, proceed.

@mpuccio, thanks for spotting this!

**Comment by mpuccio** [comment]
Perfect! Thanks a lot, I close this pull request.

**Comment by ktf** [comment]
Actually I will be in a training the whole day so it might take me a while.
