### ISSUE TITLE
ROOT6 build for O2 crashing under Ubuntu 14.04

### ISSUE THREAD

**Issue by mfasDa** [alisw/alidist#791]
After the changes in #777 the ROOT6 build for O2 is crashing for me under Ubuntu 14.04 due to a missing reference in python:

DEBUG:O2:alfa-master: Scanning dependencies of target Physics
DEBUG:O2:alfa-master: [ 81%] Building CXX object math/physics/CMakeFiles/Physics.dir/G__Physics.cxx.o
DEBUG:O2:alfa-master: CMakeFiles/PyROOT.dir/src/Pythonize.cxx.o: In function `(anonymous namespace)::StlSequenceIter(_object*)':
DEBUG:O2:alfa-master: /home/markus/alice/sw/SOURCES/ROOT/v6-10-02_O2/v6-10-02/bindings/pyroot/src/Pythonize.cxx:1086: undefined reference to `PyUnicodeUCS2_FromString'
DEBUG:O2:alfa-master: collect2: error: ld returned 1 exit status
DEBUG:O2:alfa-master: make[2]: *** [lib/libPyROOT.so.6.10.02] Error 1
DEBUG:O2:alfa-master: make[1]: *** [bindings/pyroot/CMakeFiles/PyROOT.dir/all] Error 2
DEBUG:O2:alfa-master: make[1]: *** Waiting for unfinished jobs....

**Comment by aaniin** [comment]
Hi @mfasDa , all,

I was able to compile without problems on Ubuntu 16.04. Simply did a `aliBuild --defaults o2 build O2`. All standard packages from the system, the python2 version on the build-machine is 2.7.12. 

Python reference guide reveals the concerned function `PyObject *PyUnicode_FromString(const char *u)` was introduced in 2.6
https://docs.python.org/2/c-api/unicode.html

Markus, I see in the alidist/python.sh that python > 2.7 is checked. So I guess one would have to introduce a dependency of root on python?!

Cheers,
Hans

**Comment by mfasDa** [comment]
Hi @aaniin,

I am actually not trying to use 16.04, but the previous LTS (14.04). As such it runs reproducibly into the same issue. The problem seems to be connected to the python build on ubuntu 14.04, using UCS4 instead of UCS2, however it is not clear to me where the linker error comes from. Even though the python version is not as recent as yours, it is already a 2.7 version (2.7.6), which should be sufficient.
I am also surprised it worked under 16.04 as I would assume it uses the same UCS version as 14.04. Also I would expect that the function should be transparent to the unicode version, so there must be some binary incompatibility be introduced, either on the root side or somewhere else.

Btw.: The commit in root leading to this issue was done O(October last year) and therefore not yet present in the root v6-08 branch. So the previous version still compiled.

Cheers

Markus

**Comment by aaniin** [comment]
Hi @mfasDa ,

Yes, your system provided python should be enough. On the Ubuntu 16.04, it seems I have UCS-4. Following 
https://stackoverflow.com/questions/1446347/how-to-find-out-if-python-is-compiled-with-ucs-2-or-ucs-4
```python
>>> import sys
>>> print sys.maxunicode
1114111
>>> 
```

**Comment by mfasDa** [comment]
Problem found: ROOT picked up a pyconfig.h from a different (binary-incompatible) python installation, where the unicode size was set to 2. Not sure how this happened, but with removing it the issue went away. Therefore the issue can be closed.
