### PR TITLE
bump readout v0.14.1

### PR DESCRIPTION
**Pull request by sy-c**
fix for https://github.com/alisw/alidist/pull/1363

### CODE REVIEW

**Comment by awegrzyn** [comment]
Hi,
This fails on both Mac and CC7 due to:
```
/home/awegrzyn/alice/sw/SOURCES/Readout/v0.14.1/v0.14.1/src/testROC.cxx:15:10: fatal error: ReadoutCard/Driver.h: No such file or directory
 #include <ReadoutCard/Driver.h>
```

**Comment by sy-c** [comment]
I confirm that ReadoutCard v0.9.1 broke the interface,
it works well with v0.9.0

**Comment by kostorr** [comment]
@sy-c , I removed the Driver class and the header file. Corresponding initialisations are now done with the construction of the DMA channel. I believe it's enough to remove the include and the driver initialisation part from Readout/src/ReadoutEquipmentRORC.cxx and Readout/src/testROC.cxx

**Comment by sy-c** [comment]
sure, the fix is easy, but it should be advertised beforehand when there is an incompatible interface change (and this usually implies a major version change, as recommended in https://semver.org/)

**Comment by sy-c** [comment]
readout v0.14.2 released... compilation now ok, but will have to check with a CRU
